server:
  port: 8080

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          assortment-client-oidc:
            provider: spring
            client-id: assortment-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: assortment-client-oidc
          assortment-client-authorization-code:
            provider: spring
            client-id: assortment-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: assortment.write
            client-name: assortment-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000